name: aqsaha
description: A platform to gather all university stuff together.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # The followeing adds the Google Fonts to Aqsaha App
  google_fonts: ^3.0.1

  # this used for the onBoarding screen
  smooth_page_indicator: ^1.0.0+2
  # Preferencies
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  material_design_icons_flutter: ^5.0.6996
  equatable: ^2.0.3
  # Firebase
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2

  # This used to generate a random human details
  faker: ^2.0.0
  # This is important to show the 3D video in
  youtube_player_flutter: ^8.1.0
  jiffy: ^5.0.0
  firebase_storage: ^10.3.5
  cloud_firestore: ^3.4.4
  provider: ^6.0.3
  image_picker: ^0.8.5+3
  uuid: ^3.0.6
  flutter_staggered_grid_view: ^0.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # these are some assetes used in Aqsaha App
  assets:
    - assets/images/aqsa_uni.jpg
    - assets/images/background.jpg
    - assets/images/board.png
    - assets/images/clock.png
    - assets/images/girl.jpg
    - assets/images/graduation.png

  # uncomment the following to add a custom fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

